import type { IconType } from 'react-icons';
import {
  FaChevronRight,
  FaDiscord,
  FaFacebook,
  FaGithub,
  FaInstagram,
  FaLinkedin,
  FaMoon,
  FaPinterest,
  FaReddit,
  FaRss,
  FaTelegram,
  FaThreads,
  FaWhatsapp,
  FaX,
  FaXTwitter,
} from 'react-icons/fa6';
import {
  HiArrowRight,
  HiArrowTopRightOnSquare,
  HiArrowUpRight,
  HiCalendarDays,
  HiClipboard,
  HiEnvelope,
  HiOutlineDocument,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineLink,
  HiOutlineRocketLaunch,
} from 'react-icons/hi2';
import {
  PiBookBookmarkDuotone,
  PiGridFourDuotone,
  PiHouseDuotone,
  PiImageDuotone,
  PiLinkDuotone,
  PiMoonStarsDuotone,
  PiUserCircleDuotone,
} from 'react-icons/pi';
import { SiFigma, SiJavascript, SiNextdotjs, SiSupabase } from 'react-icons/si';
import { GgNpm, LogosHuggingFaceIcon, LogosRubygems } from './customIcons';

export const iconLibrary: Record<string, IconType> = {
  ruby: LogosRubygems,
  npm: GgNpm,
  moon: PiMoonStarsDuotone,
  huggingface: LogosHuggingFaceIcon,
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  chevronRight: FaChevronRight,
  linkOut: PiLinkDuotone,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  clipboard: HiClipboard,
  rss: FaRss,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
